# Generated by Django 5.0.2 on 2024-02-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [  
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('image', models.ImageField(upload_to='post_images/', verbose_name='Image')),
                ('is_published', models.BooleanField(default=False, verbose_name='Published')),
                ('likes', models.IntegerField(default=0, verbose_name='Likes')),
                ('views', models.IntegerField(default=0, verbose_name='Views')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='When created')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='When updated')),
            ],
        ),
    ]
