# Generated by Django 5.0.2 on 2024-03-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_comment_dislike_remove_comment_likes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AddField(
            model_name='post',
            name='image_thumbnail',
            field=models.ImageField(blank=True, upload_to='post_images/', verbose_name='Мініатюра'),
        ),
    ]
