# Generated by Django 5.0.2 on 2024-04-13 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_orderproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ('id',), 'verbose_name': 'Кошик', 'verbose_name_plural': 'Кошики'},
        ),
    ]
