# Generated by Django 5.0.2 on 2024-04-13 13:25

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_cart_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='catalog/products/', verbose_name='Зображення')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основне зображення')),
            ],
        ),
    ]
