# Generated by Django 5.0.2 on 2024-04-13 13:51

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='cart',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='catalog/', verbose_name='Зображення'),
        ),
    ]
