# Generated by Django 5.0.2 on 2024-04-13 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_delete_image_cart_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Кошик', 'verbose_name_plural': 'Кошики'},
        ),
        migrations.RemoveField(
            model_name='cart',
            name='image',
        ),
    ]
